import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import PixelBackground from "@/components/PixelBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Background Stars */}
        {/* <div id="stars" aria-hidden="true" />
        <div id="stars2" aria-hidden="true" />
        <div id="stars3" aria-hidden="true" /> */}

        {/* pixel background */}

        {/* App Content */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
